import GlobalProvider from "@/components/shared/GlobalProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className="p-4 h-screen flex items-center justify-center">
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
